### ISSUE TITLE
paper code

### ISSUE THREAD

**Issue by guoyage** [ChuhuaW/SGNet.pytorch#1]
First of all, thank you for such a wonderful research. I would like to ask when you will release the code of the paper???

**Comment by ChuhuaW** [comment]
Thanks @guoyage for your interest! Code will be made available next several weeks.

**Comment by jinfagang** [comment]
@ChuhuaW Does the code ready to release now?

**Comment by ChuhuaW** [comment]
@jinfagang Thank for your interests in our paper! We are working on cleaning the codes and will be made in the next few weeks.

**Comment by daeunni** [comment]
when I can see your code :) ?

**Comment by ChuhuaW** [comment]
> when I can see your code :) ?

Thanks for your interest in our paper! We have uploaded the source codes for our project. More is on the way!

**Comment by daeunni** [comment]
Thanks!
