### ISSUE TITLE
when training

### ISSUE THREAD

**Issue by f777777** [ChuhuaW/SGNet.pytorch#10]
Hello, when I try to run, this error occurs. There is no module named "nuscenes. prediction". I found it in "lib \ utils \ eval_ utils.py : from nuscenes. prediction import convert_ local_ coords_ to_ global." I would like to know whether this module is in the installation package environment? It's not in this folder, and I didn't find this module in the installation package.Thanks!

**Comment by ChuhuaW** [comment]
Hi, this is the API provided by NuScenes (see #8 ). However, if you are not working on the NuScenes dataset, simply comment out the import line.
