### ISSUE TITLE
Visualization is not ideal(JAAD)

### ISSUE THREAD

**Issue by wuyuanmm** [ChuhuaW/SGNet.pytorch#11]
Thank you so much for releasing this awesome project.

I have done the training of the determined trajectories using the modified script. 
200 epochs, MSE_05: 85.124462; MSE_10: 333.395368; MSE_15: 1057.618436. Then I implemented the visualization.

1.  red is observed traj(center of bbox)
2. green is target traj(center of bbox)
3. blue is predict traj(center of bbox)

I found that the predicted results seem to have a large error, and I want to know if I am wrong somewhere. Thanks!
![image](https://user-images.githubusercontent.com/12526251/150094952-d01e9b60-6cd2-46cb-aac4-8c1f91aa6534.png)

![image](https://user-images.githubusercontent.com/12526251/150095182-08bd1a86-983f-43fa-b47f-329547e86539.png)

![image](https://user-images.githubusercontent.com/12526251/150095399-3fe8be59-b920-43e4-a6c3-d19a2b6a0b63.png)

![image](https://user-images.githubusercontent.com/12526251/150095506-40ee3331-aff1-46b4-ab2a-0757ef035252.png)
code is here [test_vis.zip](https://github.com/ChuhuaW/SGNet.pytorch/files/7895499/test_vis.zip)

**Comment by ChuhuaW** [comment]
Hi @wuyuanmm,

Thank you for your interest in our paper and for sharing your results with us. Note our model is a pure temporal modal, and we do not use any image or ego-motion features for JAAD. In this particular example, although the ego-vehicle remains still in the present frame, it will move forward in the next few frames (As a result, the target future trajectory is shorter or in the opposite direction of the person's movement.). It is difficult to predict the correct trajectory. However, if no ego-motion is involved, our model generate a better result (see image). ![download](https://user-images.githubusercontent.com/16619342/150230061-050b772d-0161-449a-94f0-70b0a01e922e.png)

**Comment by wuyuanmm** [comment]
Thank you very much for your reply! but I also want to know if SGnet can be trained with  the information  of ego-motion.If so, what should I do.  Thanks, I looking forward to your reply.

**Comment by ChuhuaW** [comment]
We haven't tried it on JAAD yet, but we believe it can. You can check out this paper: Unsupervised Traffic Accident Detection in First-Person Videos (github: https://github.com/MoonBlvd/tad-IROS2019). They generated the ego-motion with ORBSLAM2, and used that as additional input to the decoder. In fact, we trained SGNet on HEVI with ego-motion.

**Comment by wuyuanmm** [comment]
Thank you very much. I get it. I will try it.
