### ISSUE TITLE
Deterministic Training of PIE/JAAD

### ISSUE THREAD

**Issue by KSXGroup** [ChuhuaW/SGNet.pytorch#13]
Hi, I managed to modify your code and train the deterministic model, but the result is not as good as you reported in your paper.
I got 39.8 149.3 489.5 after 50 epochs for PIE dataset. 88.4, 357.3, 1153.4 after 50 epoch. While your paper reported in much better than this. I think I may miss some hyper parameters for training. So could you give some suggestions for deterministic training of JAAD/PIE to reproduce your result?

**Comment by segermans** [comment]
Also interested in this!

**Comment by ChuhuaW** [comment]
Hi, thanks for interesting in our paper. Could you try these two checkpoints (https://drive.google.com/drive/folders/1SskmNtf9FMn4azAxIfKXcYUgAEuVKNgR?usp=sharing)
and see if you can get similar results? I retrained them on TITAN xp 12GB for 50 epochs. 
JAAD: MSE_05: 81.949379;   MSE_10: 320.276030;  MSE_15: 1018.617409; 
PIE: MSE_05: 35.174092;   MSE_10: 137.257473;  MSE_15: 457.614542;

**Comment by KSXGroup** [comment]
> Hi, thanks for interesting in our paper. Could you try these two checkpoints (https://drive.google.com/drive/folders/1SskmNtf9FMn4azAxIfKXcYUgAEuVKNgR?usp=sharing) and see if you can get similar results? I retrained them on TITAN xp 12GB for 50 epochs. JAAD: MSE_05: 81.949379; MSE_10: 320.276030; MSE_15: 1018.617409; PIE: MSE_05: 35.174092; MSE_10: 137.257473; MSE_15: 457.614542;

Thanks for your reply and I will try it, but it seems that you don't provide the hyper-parameters and codes for deterministic training for PIE and JAAD, would you mind releasing that?

**Comment by ChuhuaW** [comment]
Also, comment out line 21 in lib/models/SGNet.py if an error occurs while loading the checkpoints.Flows aren't used in JAAD or PIE so you can safely comment it out.

`# self.flow_enc_cell = nn.GRUCell(self.hidden_size*2, self.hidden_size)`

**Comment by KSXGroup** [comment]
I just paste one training log example here for reference

ep1, MSE_05: 449.187698;   MSE_10: 1780.321155;  MSE_15: 4353.067894;  FMSE: 14130.609828;  FIOU: 0.227647 
ep1, CFMSE: 13837.172693;   CMSE: 4261.267140;  
ep3, MSE_05: 445.541013;   MSE_10: 1770.817709;  MSE_15: 4343.426615;  FMSE: 14130.603430;  FIOU: 0.233714 
ep3, CFMSE: 13834.113452;   CMSE: 4250.849759;  
ep4, MSE_05: 442.151456;   MSE_10: 1748.564755;  MSE_15: 4252.691231;  FMSE: 13775.053106;  FIOU: 0.205451 
ep4, CFMSE: 13503.029097;   CMSE: 4164.804207;  
ep5, MSE_05: 434.190144;   MSE_10: 1720.635946;  MSE_15: 4187.344003;  FMSE: 13545.196836;  FIOU: 0.193533 
ep5, CFMSE: 13280.466355;   CMSE: 4101.703430;  
ep8, MSE_05: 309.076843;   MSE_10: 1236.051520;  MSE_15: 3289.651315;  FMSE: 11696.614554;  FIOU: 0.221445 
ep8, CFMSE: 11438.976825;   CMSE: 3209.180250;  
ep9, MSE_05: 227.666479;   MSE_10: 916.519019;  MSE_15: 2309.169892;  FMSE: 7693.900274;  FIOU: 0.154086 
ep9, CFMSE: 7449.675650;   CMSE: 2230.761583;  
ep10, MSE_05: 169.021236;   MSE_10: 742.770539;  MSE_15: 2059.600003;  FMSE: 7412.891365;  FIOU: 0.164239 
ep10, CFMSE: 7166.255837;   CMSE: 1980.808950;  
ep11, MSE_05: 119.887421;   MSE_10: 368.081385;  MSE_15: 1018.614191;  FMSE: 3906.774492;  FIOU: 0.267575 
ep11, CFMSE: 3664.883034;   CMSE: 937.812580;  
ep12, MSE_05: 67.267994;   MSE_10: 254.928993;  MSE_15: 797.277620;  FMSE: 3290.164852;  FIOU: 0.274885 
ep12, CFMSE: 3062.322799;   CMSE: 722.955341;  
ep14, MSE_05: 64.912690;   MSE_10: 235.899505;  MSE_15: 726.755561;  FMSE: 2976.355538;  FIOU: 0.332351 
ep14, CFMSE: 2758.819924;   CMSE: 655.499474;  
ep15, MSE_05: 60.421142;   MSE_10: 217.432056;  MSE_15: 689.159751;  FMSE: 2872.609676;  FIOU: 0.339372 
ep15, CFMSE: 2672.582721;   CMSE: 621.612563;  
ep16, MSE_05: 60.629186;   MSE_10: 213.955677;  MSE_15: 685.550784;  FMSE: 2884.828821;  FIOU: 0.333382 
ep16, CFMSE: 2692.880890;   CMSE: 620.436207;  
ep17, MSE_05: 57.160750;   MSE_10: 216.499938;  MSE_15: 675.859559;  FMSE: 2761.743777;  FIOU: 0.314166 
ep17, CFMSE: 2570.481042;   CMSE: 611.438531;  
ep18, MSE_05: 53.750287;   MSE_10: 206.210471;  MSE_15: 658.461355;  FMSE: 2731.660943;  FIOU: 0.340990 
ep18, CFMSE: 2543.997602;   CMSE: 594.788927;  
ep19, MSE_05: 53.064178;   MSE_10: 203.640594;  MSE_15: 650.139898;  FMSE: 2684.608427;  FIOU: 0.326822 
ep19, CFMSE: 2499.110935;   CMSE: 586.956205;  
ep20, MSE_05: 50.589301;   MSE_10: 195.350834;  MSE_15: 629.731515;  FMSE: 2615.836499;  FIOU: 0.348277 
ep20, CFMSE: 2438.080035;   CMSE: 568.199579;  
ep22, MSE_05: 50.375798;   MSE_10: 187.985301;  MSE_15: 609.617136;  FMSE: 2553.690646;  FIOU: 0.342243 
ep22, CFMSE: 2382.164761;   CMSE: 549.877905;  
ep24, MSE_05: 48.368682;   MSE_10: 184.705837;  MSE_15: 593.200566;  FMSE: 2453.233296;  FIOU: 0.353392 
ep24, CFMSE: 2285.109329;   CMSE: 534.704092;  
ep25, MSE_05: 47.536897;   MSE_10: 180.553501;  MSE_15: 590.225221;  FMSE: 2478.802476;  FIOU: 0.366099 
ep25, CFMSE: 2311.888217;   CMSE: 532.425417;  
ep26, MSE_05: 46.642942;   MSE_10: 175.133695;  MSE_15: 575.047758;  FMSE: 2431.421000;  FIOU: 0.356632 
ep26, CFMSE: 2274.233300;   CMSE: 520.524581;  
ep28, MSE_05: 44.494862;   MSE_10: 169.881082;  MSE_15: 560.665354;  FMSE: 2378.101471;  FIOU: 0.380304 
ep28, CFMSE: 2233.779785;   CMSE: 510.710278;  
ep29, MSE_05: 44.338670;   MSE_10: 168.507540;  MSE_15: 556.530184;  FMSE: 2360.649180;  FIOU: 0.380622 
ep29, CFMSE: 2219.985149;   CMSE: 507.658678;  
ep30, MSE_05: 44.051423;   MSE_10: 166.552546;  MSE_15: 550.299649;  FMSE: 2334.303725;  FIOU: 0.381880 
ep30, CFMSE: 2199.104702;   CMSE: 503.209425;  
ep31, MSE_05: 43.823800;   MSE_10: 164.840327;  MSE_15: 543.639752;  FMSE: 2302.590161;  FIOU: 0.382854 
ep31, CFMSE: 2173.151631;   CMSE: 498.331671;  
ep32, MSE_05: 43.620152;   MSE_10: 163.704755;  MSE_15: 538.664427;  FMSE: 2278.094012;  FIOU: 0.382814 
ep32, CFMSE: 2154.429798;   CMSE: 495.225956;  
ep33, MSE_05: 43.372520;   MSE_10: 162.519561;  MSE_15: 534.596597;  FMSE: 2258.915075;  FIOU: 0.381870 
ep33, CFMSE: 2139.720970;   CMSE: 492.694131;  
ep34, MSE_05: 42.986599;   MSE_10: 160.804613;  MSE_15: 528.326908;  FMSE: 2229.286110;  FIOU: 0.382606 
ep34, CFMSE: 2115.051768;   CMSE: 487.934997;  
ep35, MSE_05: 42.778097;   MSE_10: 159.554327;  MSE_15: 523.833170;  FMSE: 2209.543662;  FIOU: 0.379650 
ep35, CFMSE: 2098.334256;   CMSE: 484.439645;  
ep36, MSE_05: 42.429516;   MSE_10: 158.228604;  MSE_15: 519.648128;  FMSE: 2190.993327;  FIOU: 0.377764 
ep36, CFMSE: 2083.392421;   CMSE: 481.313738;  
ep37, MSE_05: 42.189752;   MSE_10: 157.117327;  MSE_15: 515.682807;  FMSE: 2172.465089;  FIOU: 0.376696 
ep37, CFMSE: 2067.896888;   CMSE: 478.209699;  
ep38, MSE_05: 42.026859;   MSE_10: 156.236913;  MSE_15: 511.866264;  FMSE: 2153.197993;  FIOU: 0.375265 
ep38, CFMSE: 2051.296649;   CMSE: 475.166550;  
ep39, MSE_05: 41.836684;   MSE_10: 155.393448;  MSE_15: 508.664941;  FMSE: 2138.093182;  FIOU: 0.374732 
ep39, CFMSE: 2038.171102;   CMSE: 472.565944;  
ep40, MSE_05: 41.658332;   MSE_10: 154.518130;  MSE_15: 504.993652;  FMSE: 2119.895949;  FIOU: 0.374774 
ep40, CFMSE: 2021.453094;   CMSE: 469.326311;  
ep41, MSE_05: 41.494369;   MSE_10: 153.770028;  MSE_15: 502.281903;  FMSE: 2107.326718;  FIOU: 0.375562 
ep41, CFMSE: 2010.320418;   CMSE: 467.038422;  
ep42, MSE_05: 41.227068;   MSE_10: 152.849798;  MSE_15: 499.588826;  FMSE: 2095.075048;  FIOU: 0.382866 
ep42, CFMSE: 1998.716680;   CMSE: 464.551599;  
ep43, MSE_05: 41.051237;   MSE_10: 152.360885;  MSE_15: 498.704539;  FMSE: 2093.417370;  FIOU: 0.385959 
ep43, CFMSE: 1996.988133;   CMSE: 463.695547;  
ep44, MSE_05: 40.903513;   MSE_10: 151.821827;  MSE_15: 497.086970;  FMSE: 2086.948007;  FIOU: 0.386559 
ep44, CFMSE: 1991.402637;   CMSE: 462.308361;  
ep45, MSE_05: 40.783092;   MSE_10: 151.115676;  MSE_15: 494.781972;  FMSE: 2077.795251;  FIOU: 0.387068 
ep45, CFMSE: 1982.715062;   CMSE: 460.188014;  
ep46, MSE_05: 40.703222;   MSE_10: 150.838822;  MSE_15: 494.007193;  FMSE: 2074.565226;  FIOU: 0.387481 
ep46, CFMSE: 1980.249112;   CMSE: 459.634566;  
ep47, MSE_05: 40.548762;   MSE_10: 150.386108;  MSE_15: 492.776395;  FMSE: 2070.017678;  FIOU: 0.386820 
ep47, CFMSE: 1975.936429;   CMSE: 458.481782;  
ep48, MSE_05: 40.503383;   MSE_10: 150.141016;  MSE_15: 492.170460;  FMSE: 2068.286530;  FIOU: 0.387484 
ep48, CFMSE: 1975.238822;   CMSE: 458.161116;  
ep49, MSE_05: 40.396762;   MSE_10: 149.671281;  MSE_15: 490.634805;  FMSE: 2061.942694;  FIOU: 0.387450 
ep49, CFMSE: 1969.574128;   CMSE: 456.823588;  
ep50, MSE_05: 40.279356;   MSE_10: 149.270103;  MSE_15: 489.512810;  FMSE: 2057.651844;  FIOU: 0.387501 
ep50, CFMSE: 1965.865168;   CMSE: 455.864361;  
ep55, MSE_05: 39.869515;   MSE_10: 148.866592;  MSE_15: 489.398181;  FMSE: 2056.977987;  FIOU: 0.388142 
ep55, CFMSE: 1966.306894;   CMSE: 456.216178;  
ep56, MSE_05: 39.851063;   MSE_10: 148.942267;  MSE_15: 489.063550;  FMSE: 2053.540835;  FIOU: 0.387602 
ep56, CFMSE: 1963.564457;   CMSE: 456.055077;  
ep57, MSE_05: 39.831128;   MSE_10: 148.942476;  MSE_15: 488.681433;  FMSE: 2050.651116;  FIOU: 0.386801 
ep57, CFMSE: 1961.035865;   CMSE: 455.797471;

**Comment by ChuhuaW** [comment]
> > Hi, thanks for interesting in our paper. Could you try these two checkpoints (https://drive.google.com/drive/folders/1SskmNtf9FMn4azAxIfKXcYUgAEuVKNgR?usp=sharing) and see if you can get similar results? I retrained them on TITAN xp 12GB for 50 epochs. JAAD: MSE_05: 81.949379; MSE_10: 320.276030; MSE_15: 1018.617409; PIE: MSE_05: 35.174092; MSE_10: 137.257473; MSE_15: 457.614542;
> 
> Thanks for your reply and I will try it, but it seems that you don't provide the hyper-parameters and codes for deterministic training for PIE and JAAD, would you mind releasing that?

You can set the learning rate for deterministic to 1e-3, and extend epochs to 60, which might sometimes help. Or it could be just a bad seed. [Training script](https://github.com/ChuhuaW/SGNet.pytorch/files/7960821/train_deterministic.zip) for PIE is attached. Change Line 14 for JAAD.
[Here is the training log for PIE](https://github.com/ChuhuaW/SGNet.pytorch/files/7960845/pie_log.txt)

**Comment by KSXGroup** [comment]
> > > Hi, thanks for interesting in our paper. Could you try these two checkpoints (https://drive.google.com/drive/folders/1SskmNtf9FMn4azAxIfKXcYUgAEuVKNgR?usp=sharing) and see if you can get similar results? I retrained them on TITAN xp 12GB for 50 epochs. JAAD: MSE_05: 81.949379; MSE_10: 320.276030; MSE_15: 1018.617409; PIE: MSE_05: 35.174092; MSE_10: 137.257473; MSE_15: 457.614542;
> > 
> > 
> > Thanks for your reply and I will try it, but it seems that you don't provide the hyper-parameters and codes for deterministic training for PIE and JAAD, would you mind releasing that?
> 
> You can set the learning rate for deterministic to 1e-3, and extend epochs to 60, which might sometimes help. Also, try comment out the scheduler may help as well. Or it could be just a bad seed. [Training script](https://github.com/ChuhuaW/SGNet.pytorch/files/7960821/train_deterministic.zip) for PIE is attached. Change Line 14 for JAAD. Here is my [training log for PIE](https://github.com/ChuhuaW/SGNet.pytorch/files/7960845/pie_log.txt).

Thanks for suggestion, and i think you also don't make `jaadpie_train_utils.py` public, and I modified ethucy version on my own. Will it influence the result ?

**Comment by ChuhuaW** [comment]
> > > > Hi, thanks for interesting in our paper. Could you try these two checkpoints (https://drive.google.com/drive/folders/1SskmNtf9FMn4azAxIfKXcYUgAEuVKNgR?usp=sharing) and see if you can get similar results? I retrained them on TITAN xp 12GB for 50 epochs. JAAD: MSE_05: 81.949379; MSE_10: 320.276030; MSE_15: 1018.617409; PIE: MSE_05: 35.174092; MSE_10: 137.257473; MSE_15: 457.614542;
> > > 
> > > 
> > > Thanks for your reply and I will try it, but it seems that you don't provide the hyper-parameters and codes for deterministic training for PIE and JAAD, would you mind releasing that?
> > 
> > 
> > You can set the learning rate for deterministic to 1e-3, and extend epochs to 60, which might sometimes help. Also, try comment out the scheduler may help as well. Or it could be just a bad seed. [Training script](https://github.com/ChuhuaW/SGNet.pytorch/files/7960821/train_deterministic.zip) for PIE is attached. Change Line 14 for JAAD. Here is my [training log for PIE](https://github.com/ChuhuaW/SGNet.pytorch/files/7960845/pie_log.txt).
> 
> Thanks for suggestion, and i think you also don't make `jaadpie_train_utils.py` public, and I modified ethucy version on my own. Will it influence the result ?

I don't think so, as jaadpie_train_utils.py and jaadpie_train_utils_cvae.py are nearly identical except for the loss and evaluation function. Just make sure you are using the correct evaluation function (eval_jaad_pie()) and inputs.

**Comment by CrisCloseTheDoor** [comment]
> I just paste one training log example here for reference
> 
> ep1, MSE_05: 449.187698; MSE_10: 1780.321155; MSE_15: 4353.067894; FMSE: 14130.609828; FIOU: 0.227647 ep1, CFMSE: 13837.172693; CMSE: 4261.267140; ep3, MSE_05: 445.541013; MSE_10: 1770.817709; MSE_15: 4343.426615; FMSE: 14130.603430; FIOU: 0.233714 ep3, CFMSE: 13834.113452; CMSE: 4250.849759; ep4, MSE_05: 442.151456; MSE_10: 1748.564755; MSE_15: 4252.691231; FMSE: 13775.053106; FIOU: 0.205451 ep4, CFMSE: 13503.029097; CMSE: 4164.804207; ep5, MSE_05: 434.190144; MSE_10: 1720.635946; MSE_15: 4187.344003; FMSE: 13545.196836; FIOU: 0.193533 ep5, CFMSE: 13280.466355; CMSE: 4101.703430; ep8, MSE_05: 309.076843; MSE_10: 1236.051520; MSE_15: 3289.651315; FMSE: 11696.614554; FIOU: 0.221445 ep8, CFMSE: 11438.976825; CMSE: 3209.180250; ep9, MSE_05: 227.666479; MSE_10: 916.519019; MSE_15: 2309.169892; FMSE: 7693.900274; FIOU: 0.154086 ep9, CFMSE: 7449.675650; CMSE: 2230.761583; ep10, MSE_05: 169.021236; MSE_10: 742.770539; MSE_15: 2059.600003; FMSE: 7412.891365; FIOU: 0.164239 ep10, CFMSE: 7166.255837; CMSE: 1980.808950; ep11, MSE_05: 119.887421; MSE_10: 368.081385; MSE_15: 1018.614191; FMSE: 3906.774492; FIOU: 0.267575 ep11, CFMSE: 3664.883034; CMSE: 937.812580; ep12, MSE_05: 67.267994; MSE_10: 254.928993; MSE_15: 797.277620; FMSE: 3290.164852; FIOU: 0.274885 ep12, CFMSE: 3062.322799; CMSE: 722.955341; ep14, MSE_05: 64.912690; MSE_10: 235.899505; MSE_15: 726.755561; FMSE: 2976.355538; FIOU: 0.332351 ep14, CFMSE: 2758.819924; CMSE: 655.499474; ep15, MSE_05: 60.421142; MSE_10: 217.432056; MSE_15: 689.159751; FMSE: 2872.609676; FIOU: 0.339372 ep15, CFMSE: 2672.582721; CMSE: 621.612563; ep16, MSE_05: 60.629186; MSE_10: 213.955677; MSE_15: 685.550784; FMSE: 2884.828821; FIOU: 0.333382 ep16, CFMSE: 2692.880890; CMSE: 620.436207; ep17, MSE_05: 57.160750; MSE_10: 216.499938; MSE_15: 675.859559; FMSE: 2761.743777; FIOU: 0.314166 ep17, CFMSE: 2570.481042; CMSE: 611.438531; ep18, MSE_05: 53.750287; MSE_10: 206.210471; MSE_15: 658.461355; FMSE: 2731.660943; FIOU: 0.340990 ep18, CFMSE: 2543.997602; CMSE: 594.788927; ep19, MSE_05: 53.064178; MSE_10: 203.640594; MSE_15: 650.139898; FMSE: 2684.608427; FIOU: 0.326822 ep19, CFMSE: 2499.110935; CMSE: 586.956205; ep20, MSE_05: 50.589301; MSE_10: 195.350834; MSE_15: 629.731515; FMSE: 2615.836499; FIOU: 0.348277 ep20, CFMSE: 2438.080035; CMSE: 568.199579; ep22, MSE_05: 50.375798; MSE_10: 187.985301; MSE_15: 609.617136; FMSE: 2553.690646; FIOU: 0.342243 ep22, CFMSE: 2382.164761; CMSE: 549.877905; ep24, MSE_05: 48.368682; MSE_10: 184.705837; MSE_15: 593.200566; FMSE: 2453.233296; FIOU: 0.353392 ep24, CFMSE: 2285.109329; CMSE: 534.704092; ep25, MSE_05: 47.536897; MSE_10: 180.553501; MSE_15: 590.225221; FMSE: 2478.802476; FIOU: 0.366099 ep25, CFMSE: 2311.888217; CMSE: 532.425417; ep26, MSE_05: 46.642942; MSE_10: 175.133695; MSE_15: 575.047758; FMSE: 2431.421000; FIOU: 0.356632 ep26, CFMSE: 2274.233300; CMSE: 520.524581; ep28, MSE_05: 44.494862; MSE_10: 169.881082; MSE_15: 560.665354; FMSE: 2378.101471; FIOU: 0.380304 ep28, CFMSE: 2233.779785; CMSE: 510.710278; ep29, MSE_05: 44.338670; MSE_10: 168.507540; MSE_15: 556.530184; FMSE: 2360.649180; FIOU: 0.380622 ep29, CFMSE: 2219.985149; CMSE: 507.658678; ep30, MSE_05: 44.051423; MSE_10: 166.552546; MSE_15: 550.299649; FMSE: 2334.303725; FIOU: 0.381880 ep30, CFMSE: 2199.104702; CMSE: 503.209425; ep31, MSE_05: 43.823800; MSE_10: 164.840327; MSE_15: 543.639752; FMSE: 2302.590161; FIOU: 0.382854 ep31, CFMSE: 2173.151631; CMSE: 498.331671; ep32, MSE_05: 43.620152; MSE_10: 163.704755; MSE_15: 538.664427; FMSE: 2278.094012; FIOU: 0.382814 ep32, CFMSE: 2154.429798; CMSE: 495.225956; ep33, MSE_05: 43.372520; MSE_10: 162.519561; MSE_15: 534.596597; FMSE: 2258.915075; FIOU: 0.381870 ep33, CFMSE: 2139.720970; CMSE: 492.694131; ep34, MSE_05: 42.986599; MSE_10: 160.804613; MSE_15: 528.326908; FMSE: 2229.286110; FIOU: 0.382606 ep34, CFMSE: 2115.051768; CMSE: 487.934997; ep35, MSE_05: 42.778097; MSE_10: 159.554327; MSE_15: 523.833170; FMSE: 2209.543662; FIOU: 0.379650 ep35, CFMSE: 2098.334256; CMSE: 484.439645; ep36, MSE_05: 42.429516; MSE_10: 158.228604; MSE_15: 519.648128; FMSE: 2190.993327; FIOU: 0.377764 ep36, CFMSE: 2083.392421; CMSE: 481.313738; ep37, MSE_05: 42.189752; MSE_10: 157.117327; MSE_15: 515.682807; FMSE: 2172.465089; FIOU: 0.376696 ep37, CFMSE: 2067.896888; CMSE: 478.209699; ep38, MSE_05: 42.026859; MSE_10: 156.236913; MSE_15: 511.866264; FMSE: 2153.197993; FIOU: 0.375265 ep38, CFMSE: 2051.296649; CMSE: 475.166550; ep39, MSE_05: 41.836684; MSE_10: 155.393448; MSE_15: 508.664941; FMSE: 2138.093182; FIOU: 0.374732 ep39, CFMSE: 2038.171102; CMSE: 472.565944; ep40, MSE_05: 41.658332; MSE_10: 154.518130; MSE_15: 504.993652; FMSE: 2119.895949; FIOU: 0.374774 ep40, CFMSE: 2021.453094; CMSE: 469.326311; ep41, MSE_05: 41.494369; MSE_10: 153.770028; MSE_15: 502.281903; FMSE: 2107.326718; FIOU: 0.375562 ep41, CFMSE: 2010.320418; CMSE: 467.038422; ep42, MSE_05: 41.227068; MSE_10: 152.849798; MSE_15: 499.588826; FMSE: 2095.075048; FIOU: 0.382866 ep42, CFMSE: 1998.716680; CMSE: 464.551599; ep43, MSE_05: 41.051237; MSE_10: 152.360885; MSE_15: 498.704539; FMSE: 2093.417370; FIOU: 0.385959 ep43, CFMSE: 1996.988133; CMSE: 463.695547; ep44, MSE_05: 40.903513; MSE_10: 151.821827; MSE_15: 497.086970; FMSE: 2086.948007; FIOU: 0.386559 ep44, CFMSE: 1991.402637; CMSE: 462.308361; ep45, MSE_05: 40.783092; MSE_10: 151.115676; MSE_15: 494.781972; FMSE: 2077.795251; FIOU: 0.387068 ep45, CFMSE: 1982.715062; CMSE: 460.188014; ep46, MSE_05: 40.703222; MSE_10: 150.838822; MSE_15: 494.007193; FMSE: 2074.565226; FIOU: 0.387481 ep46, CFMSE: 1980.249112; CMSE: 459.634566; ep47, MSE_05: 40.548762; MSE_10: 150.386108; MSE_15: 492.776395; FMSE: 2070.017678; FIOU: 0.386820 ep47, CFMSE: 1975.936429; CMSE: 458.481782; ep48, MSE_05: 40.503383; MSE_10: 150.141016; MSE_15: 492.170460; FMSE: 2068.286530; FIOU: 0.387484 ep48, CFMSE: 1975.238822; CMSE: 458.161116; ep49, MSE_05: 40.396762; MSE_10: 149.671281; MSE_15: 490.634805; FMSE: 2061.942694; FIOU: 0.387450 ep49, CFMSE: 1969.574128; CMSE: 456.823588; ep50, MSE_05: 40.279356; MSE_10: 149.270103; MSE_15: 489.512810; FMSE: 2057.651844; FIOU: 0.387501 ep50, CFMSE: 1965.865168; CMSE: 455.864361; ep55, MSE_05: 39.869515; MSE_10: 148.866592; MSE_15: 489.398181; FMSE: 2056.977987; FIOU: 0.388142 ep55, CFMSE: 1966.306894; CMSE: 456.216178; ep56, MSE_05: 39.851063; MSE_10: 148.942267; MSE_15: 489.063550; FMSE: 2053.540835; FIOU: 0.387602 ep56, CFMSE: 1963.564457; CMSE: 456.055077; ep57, MSE_05: 39.831128; MSE_10: 148.942476; MSE_15: 488.681433; FMSE: 2050.651116; FIOU: 0.386801 ep57, CFMSE: 1961.035865; CMSE: 455.797471;

Hi, did you clone the 'JAAD 2.0' repo from the JAAD's github and preprocessed the data directly by SGNet's program? I did in this way and use the data from `data_cache/jaad_database.pkl` as input. Strangely, both deterministc and cvae results are much worse than paper's. My MSE_0.5 is almost 90 in cvae and 800 in deterministic after 50 epoch. Could you please tell me how you implement that?
