### ISSUE TITLE
Paper question: 1.5 second MSE of PIE on JAAD dataset 

### ISSUE THREAD

**Issue by segermans** [ChuhuaW/SGNet.pytorch#15]
Hi,

I got another question regarding the paper (hope you do not mind me dropping it here): the performance of the PIE_traj method on JAAD for the 1.5 Second prediction horizon is indicated at 1280 MSE. However, according to the PIE authors themselves the performance is 1248 MSE on this particular prediction horizon. The mentioned performance in your paper on all other prediction horizons for all metrics (CMSE & CFMSE) on JAAD is equal to the values mentioned by the PIE authors themselves. Is there a particular reason why you changed the 1.5 second MSE ? Reproducibility or typo?

Looking forward to your response. Cheers, Seger

**Comment by ChuhuaW** [comment]
We follow to the benchmark in the Bi-Trap paper, although it is possible that there is a typo in their paper as well.
