### ISSUE TITLE
CPU RAM usage increasing for every epoch 

### ISSUE THREAD

**Issue by GuttinRibeiro** [ChuhuaW/SGNet.pytorch#16]
Hi!

First of all, I really enjoyed your paper. Unfortunately, I've been trying to train your model on PIE, but I always get OOM errors. I didn't change anything other than commenting out the lines importing and using the nuScenes toolkit.

My computer only has 16 GB of RAM and 2 GPUs with 11 GB of VRAM each. I reduced the batch size from 128 to 16 and the number of workers from 8 to 2. However, after step 216/2701 in epoch 1, the code simply starts to consume approximately 6 MB of memory per iteration and keeps doing it until I run out of memory. Your code seems right in terms of avoiding adding losses to lists without calling "loss.item()". I really don't know what's going on. I really appreciate it if you could give me any advice on this issue. Thanks.

**Comment by chrisphum** [comment]
Hey! I'm also having trouble with the program running out of GPU memory extremely early in the training phase. Did you find a solution?

**Comment by ChuhuaW** [comment]
Hi @GuttinRibeiro and @chrisphum, thanks for your interesting in our paper. I'm assuming you are training the CVAE model. 
`python tools/pie/train_cvae.py --gpu 1,2 --dataset PIE --model SGNet_CVAE --batch_size 16 --num_workers 2` I used the above command to test the code on two TITAN xp 12GB, but was unable to reproduce the issue. The memory usage is constantly 4349MiB and 4245MiB. Just want to make sure you which memory your are referring to? GPU or CPU? And could you please share your pytorch version?

**Comment by chrisphum** [comment]
Wow thanks for the quick update! I definitely wrote in early because I did eventually solve the issue by first) making sure CUDA was working correctly, and second) dropping the batch_size to 64 and the hidden_layer_size to 128. Strangely, a hidden_layer_size of 32 consumes more memory than 128. Any thoughts on this?
Also, my memory errors are related to GPU memory.
Everything works now. Thanks for the code and for making this awesome project :)

**Comment by GuttinRibeiro** [comment]
Hi @ChuhuaW, thanks for your response. I cannot reproduce the issue I reported. The problem I was facing was related strictly to the CPU RAM and I followed your recommendations to create and activate a virtual environment before running your code. 

I was measuring the increase in RAM for each step in your training function as shown below:

`def train(model, train_gen, criterion, optimizer, device):
    pid = os.getpid()
    prev_mem = 0
    model.train() # Sets the module in training mode.
    total_goal_loss = 0
    total_cvae_loss = 0
    total_KLD_loss = 0
    loader = tqdm(train_gen, total=len(train_gen))
    with torch.set_grad_enabled(True):
        for _, data in enumerate(loader):
            batch_size = data['input_x'].shape[0]
            input_traj = data['input_x'].to(device)
            target_traj = data['target_y'].to(device)
            all_goal_traj, cvae_dec_traj, KLD_loss, _  = model(inputs=input_traj, map_mask=None, targets=target_traj)
            cvae_loss = cvae_multi(cvae_dec_traj,target_traj)
            goal_loss = criterion(all_goal_traj, target_traj)

            total_goal_loss += goal_loss.item()* batch_size
            total_cvae_loss += cvae_loss.item()* batch_size
            total_KLD_loss += KLD_loss.mean().item()* batch_size

            train_loss = goal_loss + cvae_loss + KLD_loss.mean()

            # optimize
            optimizer.zero_grad()
            train_loss.backward()
            optimizer.step()
            
            
            cur_mem = (int(open('/proc/%s/statm'%pid, 'r').read().split()[1])+0.0)/256
            add_mem = cur_mem - prev_mem
            prev_mem = cur_mem
            loader.set_postfix(mem=add_mem)
            print("added mem: {} M".format(add_mem))

    total_goal_loss /= len(train_gen.dataset)
    total_cvae_loss/=len(train_gen.dataset)
    total_KLD_loss/=len(train_gen.dataset)
    
    return total_goal_loss, total_cvae_loss, total_KLD_loss`
    
    To run your model, I was using `python tools/pie/train_cvae.py --gpu 0 --dataset PIE --model SGNet_CVAE --batch_size 16 --num_workers 2`. Even though my computer has 2 GPUs, we keep the policy to use only one GPU when training as all computers in my lab are shared with other students. I know this may sound suspect, but I can assure you only I was using the computer when I reported the issue. Anyway, I'll keep using your code and I can put you in contact again if I face the same error again. Thanks!
