### ISSUE TITLE
Deterministic training and evaluation codes for PIE and JAAD

### ISSUE THREAD

**Issue by thisishale** [ChuhuaW/SGNet.pytorch#18]
Thank you very much for sharing the code. Are you going to share deterministic training and evaluation codes for PIE and JAAD in the future? I could not find it under tools/pie, tools/jaad.

**Comment by ChuhuaW** [comment]
Hi @thisishale,

Thanks for your interest in our paper. Yes, we will, and we apologize for the delay. Meanwhile, you could try modifying ETHUCY's deterministic training code for JAAD/PIE, they should be quite similar.
