### ISSUE TITLE
has the file of train_deterministic.py been delete from git

### ISSUE THREAD

**Issue by SimonQi1** [ChuhuaW/SGNet.pytorch#4]
when I run the command ：python tools/jaad/train_deterministic.py --gpu $CUDA_VISIBLE_DEVICES --dataset JAAD --model SGNet
why train_deterministic.py was deleted from this repo

**Comment by ChuhuaW** [comment]
It is actually pretty similar to the CVAE version for deterministic experiments on JAAD and PIE. We'll upload deterministic.py later, however you can modify the code based on the CVAE in the meantime.

**Comment by q517470045** [comment]
> 它实际上与用于 JAAD 和 PIE 的确定性实验的 CVAE 版本非常相似。我们稍后会上传 deterministic.py，但是您可以同时根据 CVAE 修改代码。

Thank you!

**Comment by werdnabae** [comment]
> Will relase later

Has this code been released yet?

**Comment by ChuhuaW** [comment]
> > Will relase later
> 
> Has this code been released yet?

It is almost identical to the CVAE training script. I create I [gist ](https://gist.github.com/ChuhuaW/d5812e54db3404bffbc7723d13164ce6) here. Please check it out. Thanks!
