### ISSUE TITLE
Run train_cave.py on win10, why there is no result?

### ISSUE THREAD

**Issue by yanshuaibupt** [ChuhuaW/SGNet.pytorch#5]

**Comment by ChuhuaW** [comment]
> 

Thank you for your interest in our paper! Could you please provide more  details of the issue? What do you mean by no results?

**Comment by yanshuaibupt** [comment]
The code directory is as follows:
-configs
-data
    -JAAD
-lib
-eval_cave.py
-train_cave.py
I put both configs and lib under tools\jaad, because I encountered an import error prompt in anaconda.   
When I run python tools/jaad/train_cvae.py --gpu cuda --dataset data/JAAD --model SGNet_CVAE at the prompt, there is no printing information, and the program ends directly without an error.

**Comment by ChuhuaW** [comment]
For the import error, you may want to try `export PYTHONPATH=$PWD' under './SGNet.pytorch'.
For '--gpu' flag, you should use your gpu index, since we need it to set variable 'CUDA_VISIBLE_DEVICES'. If the problem persists, I recommend evaluating the code with breakpoints (e.g., pdb). Thanks!

**Comment by yanshuaibupt** [comment]
Thanks，I found some python package call problems. Changing the relative references of SGNet.py/SGNet_CAVE.py and other files to absolute references can solve the reference problem on win10.
