### ISSUE TITLE
Hi, it should be my fault, I didn't find nuscenes.prediction in the from nuscenes.prediction import convert_local_coords_to_global

### ISSUE THREAD

**Issue by S1tephen** [ChuhuaW/SGNet.pytorch#8]

**Comment by ChuhuaW** [comment]
Hi, this is the function provided by NuScenes API, you can find it [here](https://github.com/nutonomy/nuscenes-devkit/blob/84eda0ef3c0c1ae5f5349d846b56bc1c1c75791a/python-sdk/nuscenes/prediction/helper.py). However, if you are not working on the NuScenes dataset, simply comment out the import line.
